# Veraison maintainers file
#
# This file lists the maintainers of the Veraison project.
#
[maintainers]

# Core maintainers of the project.

    [maintainers.core]
    people = [
      "simonfrostarm", 
      "thomasfossati",
      "yogeshdeshpande",   
      "manugupta",  
    ]

[people]

# A reference list of all people associated with the project.

    [people.simonfrost]
    Name = "Simon Frost"
    Email = "simon.frost@arm.com"
    GitHub = "simonfrost-arm"

    [people.sergeitrofimov]
    Name = "Sergei Trofimov"
    Email = "sergei.trofimov@arm.com"
    GitHub = "setrofim"

    [people.thomasfossati]
    Name = "Thomas Fossati"
    Email = "thomas.fossati@arm.com"
    GitHub = "thomas-fossati"

    [people.yogeshdeshpande]
    Name = "Yogesh Deshpande"
    Email = "yogesh.deshpande@arm.com"
    GitHub = "yogeshbdeshpande"

    [people.manugupta]
    Name = "Manu Gupta"
    Email = "manu.gupta@arm.com"
    GitHub = "mangup01"


